[2025-07-03T04:02:49.536+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2025-07-03T04:02:44+00:00 [queued]>
[2025-07-03T04:02:49.542+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2025-07-03T04:02:44+00:00 [queued]>
[2025-07-03T04:02:49.542+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-07-03T04:02:49.542+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-07-03T04:02:49.542+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-07-03T04:02:49.550+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2025-07-03 04:02:44+00:00
[2025-07-03T04:02:49.552+0000] {standard_task_runner.py:55} INFO - Started process 4322 to run task
[2025-07-03T04:02:49.555+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'manual__2025-07-03T04:02:44+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/email_dag.py', '--cfg-path', '/tmp/tmpvvdprlqt']
[2025-07-03T04:02:49.556+0000] {standard_task_runner.py:83} INFO - Job 83: Subtask tsk4
[2025-07-03T04:02:49.595+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 manual__2025-07-03T04:02:44+00:00 [running]> on host a5fcee7378f1
[2025-07-03T04:02:49.634+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=aws@evoluth.com.br
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2025-07-03T04:02:44+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-07-03T04:02:44+00:00
[2025-07-03T04:02:49.635+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-03T04:02:49.635+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2025-07-03T04:02:49.642+0000] {subprocess.py:86} INFO - Output:
[2025-07-03T04:02:49.643+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-03T04:02:49.650+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-03T04:02:49.653+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20250703T040244, start_date=20250703T040249, end_date=20250703T040249
[2025-07-03T04:02:49.660+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 83 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 4322)
[2025-07-03T04:02:49.694+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-07-03T04:02:49.709+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
